In [5]:
import sys
!{sys.executable} -m pip install numpy_ringbuffer

  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
You are using pip version 9.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [40]:
import numpy as np
from numpy_ringbuffer import RingBuffer

win_size=5

W_A = np.zeros(win_size) + 1
W_B = np.zeros(win_size)

r = RingBuffer(10, dtype=(np.float, win_size))

print(W_A)
print(W_B)
r.appendleft(W_A)
r.appendleft(W_B)
print(np.array(r)) 

[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]
